// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = angular.module("plunker", ["jonniespratley.angularWebSpeechDirective"]);

  app.controller("MainCtrl", function($scope) {
    return $scope.speech = {
      maxResults: 25,
      continuous: true,
      interimResults: true
    };
  });

}).call(this);
